### ISSUE TITLE
Typescript : SearchResponse "hits.total" @types probleme

### ISSUE THREAD

**Issue by xrobert35** [elastic/elasticsearch-js#1002]
Hello,

I'm using elasticsearch javascript client with Typescript but I've got a probleme with the SearchResponse type description which tell me that "hits.total" is a number. But when I receive the response from elasticsearch it return me this :

![image](https://user-images.githubusercontent.com/33020856/68694645-d0c56300-0579-11ea-972b-1ebb02ea07ad.png)

Here is the type definition from the @types package :
![image](https://user-images.githubusercontent.com/33020856/68694656-d91d9e00-0579-11ea-97fc-4a939f47a9ed.png)

I'm using elasticsearch : 7.4.2 (on docker)
In my package.json : elasticsearch 16.5.0 and @types/elasticsearch : 5.0.36

Any idea ?

Thanks

## Your Environment

- *node version*: 12
- elasticsearch 7.4.2  (officiel docker image)
- *os*: Linux (ubuntu 19)
- elasticsearch 16.5.0
- @types/elasticsearch : 5.0.36

**Comment by xrobert35** [comment]
Hello,

I have also read the documentation : 

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-request-body

which indicate that "hits" should contain an object total of this type : 

```
hits {
    total : {
       value : number;
       relation: string;
    }
    ...
}
```

Thanks,

tell me if i can help with a PR

**Comment by delvedor** [comment]
Hello! We do not maintain the type definitions on DefinitelyTyped, it's a community project. As far as I know, the types you can find there are outdated and works only with Elasticserarch v5.

Since you are using the legacy client, I would recommend you to [migrate](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/breaking-changes.html) to the new one, which also ships the type definitions *(be aware that the request and response bodies are not included yet).*
