### ISSUE TITLE
Worse performance when enabling compression (on GCP + Elastic Cloud)

### ISSUE THREAD

**Issue by tomsquest** [elastic/elasticsearch-js#1041]
## 🐛 Bug Report

It seems that using the cloud authentication when creating the `Client` (instead of specifying an url) degrades performance in our case.

With an URL, the 90 percentile is around `80ms`.
With a Cloud ID, the 90 percentile is around `120ms`.

This is reproducible : I can switch from an URL to a Cloud ID (see code below) and our perf test reports a performance degradation as seen above.

I have read that the `cloud` scheme enables compression and such, maybe this is the cause of the problem.

## To Reproduce

Steps to reproduce the behaviour:

Creating the client:

```
new Client({
      cloud: {
        id: this.config.cloudId(),
        username: this.config.username(),
        password: this.config.password()
      },
      auth: {
        username: this.config.username(),
        password: this.config.password()
      }
    })
```

Previous code:

```
      return new Client({
        node: this.config.url()
      });
    }
```

## Expected behavior

Performance should be the same in both case (connect with `cloud` or `node`).

## Your Environment

- *node version*: 10.17.0
- `@elastic/elasticsearch` *version*: 7.5.0
- Elasticsearch Cloud : 7.5.1
- Google App Engine

**Comment by tomsquest** [comment]
As per the code, there is no magic with the `cloud` connection, it only enables gzip and `TLSv1_2_method`. I think I may be able to the time on monday to give it a test (eg. enable gzip with a `url` connection and see if the performance are worse).

**Comment by tomsquest** [comment]
I re-run some tests this morning and my conclusion is that this is **the `compression: gzip` option that degrades the performance**.
The `suggestCompression` option has no strong impact.

Here is the troublesome code:

```js
new Client({
        node: this.config.url(),

        compression: "gzip", // perf degrades
        // suggestCompression: true, // no impact
 });

```

For info, we are on Google App Engine connected to Elastic Cloud.

**Comment by delvedor** [comment]
Hello!
How are you running the benchmarks? Can you share some code that I can run?

If you use the cloud Id instead of the plain url the difference (as you have discovered) is that the client forces TLS v1.2 and enables the compression ([docs](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html#_elastic_cloud)), then it also uses the Cloud Connection Pool, which skips entirely all the overhead related to the connection handling.

Side note: there is no need to put the authentication credentials inside the `cloud` configuration object, the top-level `auth` is enough :)
I also assume that you were using the authentication before as well.

**Comment by tomsquest** [comment]
Hi @delvedor ,
I cannot share much (corporate project) but I can give you some details.

As per your comment, two things:
- I will rename this issue with something about compression decreasing performance (your are right, this is not an issue with the cloud option)
- the performance decrease is quickly reproducible by enabling `compression: true` when creating the client, even when connecting with a `node: "https://user:pass@elasticcloud...".
At this point, I revert my code and use, as before, the `node` option embedding the credentials.

For the performance test, it is very classical: 
- JMeter run by Blazemeter. ~500K queries, 30minutes (+ ramp-up), 100 RPS max, 350 VU. 
- The API receives the query string and fires some queries
- The only change between the perf tests I ran is the compression, as written above.

So I don't know how we can advance here and how to troubleshoot the compression problem with GCP/Elasticcloud. :disappointed:

**Comment by delvedor** [comment]
Hello! I've invested some time trying to reproduce the issue you are encountering.
I've used [national-es-bulk-index.json](https://github.com/elastic/search-ui/blob/master/examples/elasticsearch/data/national-es-bulk-index.json) as dataset and the query was:
```js
query: {
  match: { description: 'fossils' }
}
```
The clients were running behind a tiny Node.js http server, one with compression enabled and one with compression disabled.
You can find the full code in [this gist](https://gist.github.com/delvedor/27d1f5b2ecbe2a6fa37fce9e9abf5411).

I've used [autocannon](https://github.com/mcollina/autocannon) for benchmarking with a 5 seconds test, 100 connections and 10 pipelining factor.

In both localhost and Google App Engine, the client with compression enabled was faster.
We've talked about possible causes internally, and there may be multiple scenarios that might result in a slower connection with compression enabled. As we don't have the full picture of all actors in play, it's hard to make an educated guess. Can you confirm no other load balancers, firewalls or waf's are intercepting the connection?

If you see that your performance degrades with compression enabled, then disable it probably is the best choice. We have it as default because it's considered a best practice with Elastic Cloud, but there might be some cases (such as yours) where this it does not apply :)

**Comment by tomsquest** [comment]
Hey thanks @delvedor to have taken some times to check this.

I will try to reproduce this with what you have given, in the following days.

1. First test, on GAE, deploy your gist and test the actual performance
1. Use a larger dataset, maybe ours
1. Use a larger query set with a larger dataset
1. Use Nest+Fastify as the http server

Test will be run from Blazemeter as it is easier for me and I won't run a perf test from my laptop :)
