### ISSUE TITLE
Memory leak on index iteration

### ISSUE THREAD

**Issue by brauliobo** [elastic/elasticsearch-js#1093]
## 🐛 Bug Report
Just calling index for thousands of files to index causes it to eventually cause node to raise `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

Just removing the elasticsearch search index call makes memory stable at 450mb over time.

BTW, I don't see any CPU usage of the elasticsearch daemon, is it waiting for the loop to finish?

## To Reproduce
```js
for (const f of fs.readdirSync(this.articlesDir)) {
  this.article(id).then(async obj => {
    this.client.index({index: this.name, body: obj, refresh: 'waitFor'})
  })
}
```
Adapted from https://github.com/brauliobo/biochemical-db/blob/master/scrapers/pubmed/pubmed.es6#L34

## Expected behavior
Not to leak memory when I add the index call to ElasticSearch at https://github.com/brauliobo/biochemical-db/blob/master/scrapers/pubmed/pubmed.es6#L26

## Your Environment

- *node version*: 13.9;0
- `@elastic/elasticsearch` *version*: 16.6.0
- *os*: ArchLinux

**Comment by delvedor** [comment]
Hello! From your code snippet, it looks like that the problem is related to the fact that you are creating many promises and never assigning them a catch handler. Also, the function you are using inside `then` is not returning the promise from the client, so you have no way to track its execution.

My recommendation would be to refactor the code entirely and use a bulk request for indexing the data. Furthermore, I highly recommend moving to the new  Node.js client, you can read [this page](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/breaking-changes.html) to help you in the transition.
