### ISSUE TITLE
Surface sniffing issues

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch-js#1253]
Currently, the [sniffing logic](https://github.com/elastic/elasticsearch-js/blob/1a7968aba3bbbd9660d582db2252eeafa4b23260/lib/Transport.js#L356-L396) is very optimistic, and it assumes that the ES response is correct and the user has the right permissions. Unfortunately, this does not always apply, and debug this kind of situation is rather complex.

The client should do a better job exposing this issue and offer actionable items for the users.

Related: https://github.com/elastic/elasticsearch-js/issues/923 https://github.com/elastic/elasticsearch-js/issues/1178 https://github.com/elastic/elasticsearch-js/issues/1230

**Comment by praneeth14** [comment]
Below issue I commented on in this issue #1230, but this seems to be an open issue for tackling i.e reposting same here

I am able to reproduce issue #1230 and faced this issue in my production service. Even though we give multiple nodes, when sniffing is enabled, the above error will come whenever we onboard a new node to the cluster. Whenever we onboard a new node **_nodes/_all/http** is giving the newly onboarded node details without having **http** info for ~10-15 seconds. 
Because of this ES client tries to update the connection pool every sniffingInterval ms configured, where it will break and my service will be in crash loop because of this. We should check whether **http** is present or not before checking **publish_address** directly.

### Environment
**ES Version:** 7.6.0
**ES Client version:** 7.16.0
**Node Version:** 14.x
**Client Options:**
```
const esClient = new Client({
    nodes: [node1, node2, node2],
    sniffInterval: 5000,
    sniffOnConnectionFault: true,
    maxRetries: 5,
    requestTimeout: 60000
});
```

### Reproducing steps
1. Connect to the existing cluster from the node js client using above-mentioned client options
2. Onboard a new node to the cluster
3. After some seconds the node js client will throw an error and the script will crash

### Expected behavior
The client should skip the node which doesn't have http info by adding a check before directly accessing the publish_address

The newly added node has only this info in the _node/_all/http response (doesn't have http object)
```
{
            "name": "node4",
            "transport_address": "ip:9300",
            "host": "ip",
            "ip": "ip",
            "version": "7.6.0",
            "build_flavor": "default",
            "build_type": "deb",
            "build_hash": "7f634e9f44834fbc12724506cc1da681b0c3b1e3",
            "roles": [
                "ingest",
                "data",
                "ml"
            ],
            "attributes": {
                "ml.machine_memory": "33383047168",
                "ml.max_open_jobs": "20",
                "xpack.installed": "true"
            }
}
```

**Comment by JoshMock** [comment]
https://github.com/elastic/elasticsearch-js/issues/1178 and https://github.com/elastic/elasticsearch-js/issues/1230 have been fixed/closed, but addressing the situation where the ES user doesn't have the permissions needed to get the data needed for sniffing to work correctly is still worth addressing.
