### ISSUE TITLE
Sanitize queries in the Lucene querystring syntax

### ISSUE THREAD

**Issue by walshe** [elastic/elasticsearch-js#1265]
Hi,

just wondering if this library handles sanitization of input values ? Is it possible for a malicious value to run some sort of smart query on the index ?

**Comment by delvedor** [comment]
Hello!
Nope, this library does not run any validation on queries. I would strongly recommend **not** to allow externals users to send Elasticsearch queries, but the backend should craft them each time.

This library does protect you in case there is a malicious document store in Elasticsearch, bu using [secure-json-parse](https://www.npmjs.com/package/secure-json-parse).

**Comment by walshe** [comment]
I dont allow them to send in queries however they could try to sneak a query into an input field. Anyway, in the end I used elasticsearch-sanitize for cleaning the values I use in my http elastic queries..


e.g.

`const sanitize = require("elasticsearch-sanitize");`

`must.push({
          simple_query_string: {
            query: sanitize(value),
            default_operator: "and",
          },
        });`

**Comment by delvedor** [comment]
Oh, you mean the `q` parameter of the search API, spotty, I didn't understand that.
The answer is still no, but it could be a nice feature.

**Comment by delvedor** [comment]
I've talked about this internally, and the recommendation is to use the [simple query string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#simple-query-string-syntax) where you can limit which flags can be used. But use the  `simple_query_string` only if you need logic grouping, otherwise use a more targetted `match` or `multi_match` query :)
