### ISSUE TITLE
Delete by query deleting all objects in the json document

### ISSUE THREAD

**Issue by nmdis1999** [elastic/elasticsearch-js#1273]
Hi, so I was trying deleteByQuery API query on data with json document consisting of following format:
```
{
        "partId": "PI-1781",
        "name": "Diksha Jha",
        "relationshipId": "REL-11345",
        "engagePartyId": "EN-756",
        "email": "Jha.Diksha@bnymellon.com",
        "address": "Apartment rivera, Noida",
        "phone": "987-222-1872",
        "activeStatus" : "Ä" 
    }

```

I am sending partId in body (from postman), there are an issue. Instead of deleting a particular query it deletes every object inside the index. I am not able to understand what am I doing wrong here.Can you please help?
```
app.get('/delete_account', function (req, res) {
  let body = {
    size: 200,
    from: 0,
    query: {
      match: {
        partId: req.body.partId
      }
    }
  }
  // perform the actual search passing in the index, the search query and the type
  client.deleteByQuery({
    index: 'bank',
    body: {
      query: {
        match: {
          partId: req.body.partId
        }
      }
    }
  }
.then(results => {
      res.send("Success\n");
    })
    .catch(err => {
      console.log(err)
      res.json([]);
      console.log('\n')
    });
});
```

**Comment by delvedor** [comment]
Hello! What version of Elasticsearch and the client are you using?

**Comment by senatet** [comment]
@nmdis1999 , what is the mapping of your partId? If it is mapped as both `text` and `keyword` 
as is the case for most auto-generated string mappings, then your query would most likely match all documents since tokenizing partId likely leads to `"P1"` and `"1781"` tokens being generated, which I am guessing match most, if not all of your documents, leading to all of them to be removed.

To find the exact mapping for `partId`, you can run:
`GET bank/_mapping/field/partId`

```json 
{
 "bank" : {
    "mappings" : {
      "partId" : {
        "full_name" : "partId",
        "mapping" : {
          "partId" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      }
    }
  }
}
```

To match a specific document, you can either re-index partId as type `keyword`, and match on that when deleting, or specifically target the `keyword` field in this manner:
```javascript
  // perform the actual search passing in the index, the search query and the type
  client.deleteByQuery({
    index: 'bank',
    body: {
      query: {
        match: {
          'partId.keyword': req.body.partId
        }
      }
    }
  }
```

**Comment by nmdis1999** [comment]
@senatet : Right, I mapped it to text. Your comment make sense, I tried it and now it works fine. Thank you :)

**Comment by delvedor** [comment]
Thank you for helping out @senatet!
