### ISSUE TITLE
Limiting the number of open connections/sockets

### ISSUE THREAD

**Issue by yuvalg99** [elastic/elasticsearch-js#1278]
Hello guys!
When I'm doing some requests (like search, cat ..) on my cluster, the sockets of the requests are still alive after the requests. every request opens new connection (You can check it with lsof).
How can i limit the number of the connections who are alive?

**Comment by delvedor** [comment]
Hello! Can you provide a snippet of code to reproduce your issue?
The client does keep open sockets, as it's using a keep-alive agent to avoiding the need to create a new connection each time and waste time.
You can use the following command to see how many connections have been opened against Elasticsearch:

```
curl localhost:9200/_nodes/stats/http?filter_path=nodes.*.name,nodes.*.http | jq .

```
You will see something like this:

```json
{
  "nodes": {
    "[node-id]": {
      "name": "[node-name]",
      "http": {
        "current_open": 1,
        "total_opened": 1
      }
    }
  }
}
```

The `current_open` represent the open HTTP connections at that moment, while the `total_opened` represents all the HTTP connection opened during time.
In a good scenario, the first value should be "stable", so you should not expect it to change massively, which also means that a single read is "meaningless".
The second value can increase, but very slowly.

Let's take this example:
```js
'use strict'

const { Client } = require('@elastic/elasticsearch')

const client = new Client({ node: 'http://localhost:9200' })

client.cluster.health((err, result) => {
  if (err) throw err
  client.cluster.health((err, result) => {
    if (err) throw err
    client.cluster.health((err, result) => {
      if (err) throw err
      client.cluster.health((err, result) => {
        if (err) throw err
        client.cluster.health((err, result) => {
          if (err) throw err
          console.log(result)
          console.log(
            Object.keys(client.connectionPool.connections[0].agent.sockets),
            Object.keys(client.connectionPool.connections[0].agent.freeSockets)
          )
          setTimeout(() => console.log('done'), 10000)
        })
      })
    })
  })
})
```

If you run the code above and the curl command, you should expect to see 3 `current_open` and 3 + n `total_opened`. Because the client will open two sockets and the third one is the curl command.
If you run the command above multiple times, you will see the `total_opened` increasing, which is right, as there is no reuse of connections between each run.

Same goes if you use `lsof -i tcp:9200 -n -P` with the code above, you should expect to see 2 open sockets.

By default, the HTTP agent allows to open up to 512 sockets:

https://github.com/elastic/elasticsearch-js/blob/cf172d79379d1926ae7b0c96b6219c98828520ba/lib/Connection.js#L60-L66
You can change this by updating the HTTP agent configuration:

```js
const client = new Client({
  node: 'http://localhost:9200',
  agent: {
    maxSockets: 1,
    maxFreeSockets: 1
  }
})
```

You can find the client configuration doc [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-configuration.html).

On a final note, the default configuration is battle-tested and works well in most situations, so it would be nice to see the snippet that is causing the issue in your case, and also if you can expand what are your expectations when talking about *"How can i limit the number of the connections who are alive?"*.

**Comment by HayDegha0917** [comment]
I seem to have a similar issue. Is there no upper limit on the number of connections in the client connection pool? Scanning through the code, it seems to just add connections.

**Comment by delvedor** [comment]
Hello @HayDegha0917!
Just to be clear about the language:
With `connection` we mean a representation of a Node in the client, based on the client configuration, you might have from 1 to the number of instances of Elasicsearch connections in the client pool.

Every connection can open from 1 to a configurable (default to 512) number of sockets against a single node of Elasticsearch.

If you want to configure how many sockets each connection will open, you need to work with the `agent` configuration:
```js
const client = new Client({
  node: 'http://localhost:9200',
  agent: {
    maxSockets: 256,
    maxFreeSockets: 256
  }
})
```
