### ISSUE TITLE
Performance of `Client#child`

### ISSUE THREAD

**Issue by kobelb** [elastic/elasticsearch-js#1290]
Kibana uses [`Client#child`](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.x/child-client.html) to create an instance of the Elasticsearch client that has the authentication headers for the current end-user. As such, almost every single HTTP request to Kibana will end up calling `Client#child`. While doing some load testing of Kibana, the performance of `Client#child` is looking like a bottleneck.

During a load-test where 1000 users hit a simple HTTP Kibana API which performs authentication, I'm seeing approximately 5% of the CPU time being spent within `Client#child`:

<img width="1910" alt="Screen Shot 2020-08-24 at 2 03 47 PM" src="https://user-images.githubusercontent.com/627123/91096301-acbba580-e612-11ea-82f3-bca8976a94ae.png">

The biggest culprits appear to be the use of `Object.assign` and [ESAPI](https://github.com/elastic/elasticsearch-js/blob/51ab5b0b00ced5f73d9a2ff2e0e15b43f974ab53/api/index.js#L24). 

There are some situations where Kibana can not call `Client#child` until it's absolutely needed, which definitely helps, but if we can optimize the performance of `Client#child` it will greatly help the general performance of Kibana.

If it's not feasible to improve the performance of `Client#child`, Kibana can also potentially take advantage of the overloaded methods which support the `TransportRequestOptions`, but there are some potential complications with this approach.

**Comment by restrry** [comment]
@delvedor I don't know whether that helps much, but `context` inheritance implemented in https://github.com/elastic/elasticsearch-js/pull/1256 is not needed anymore.
The initial plan to implement Audit logging for Elasticsearch requests has been withdrawn https://github.com/elastic/kibana/pull/74640#issuecomment-677930361
I'm going to close my PR https://github.com/elastic/kibana/pull/71228/files#diff-735c304f3a374c21bed52dedab88917aR88

**Comment by delvedor** [comment]
Hello! I'll look into this, thanks for reporting!

**Comment by roncohen** [comment]
@delvedor thanks for picking this up.

In one of our Fleet tests, using a hacked together Elasticsearch client instead of the normal client, makes it possible for us to go from ~6000 agents to ~20k agents supported. There are some other limitations that make it difficult to support that many agents at the moment, but improving this would be a big deal for us.

Do you have any timeline for when you'll be able to work on this?

**Comment by joshdover** [comment]
It seems that the `Object.assign` behavior could be replaced with normal prototype inheritance instead. That way, not all the values have to be copied and JS can just walk the prototype chain to find the value. This may require that these option properties are not writeable so that code can't change the parent client's options and affect child clients.

**Comment by delvedor** [comment]
@joshdover I'm already working in that direction and I got nice results :)
I'll share something soon!
