### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined in node_modules/@elastic/elasticsearch/index.js:7

### ISSUE THREAD

**Issue by spyderman4g63** [elastic/elasticsearch-js#1345]
## 🐛 Bug Report

TypeError: Cannot read property 'split' of undefined in `node_modules/@elastic/elasticsearch/index.js:7`

## To Reproduce

- `npx create-react-app test-app`
- `cd test-app`
- `npm install @elastic/elasticsearch`
- edit ./src/App.js to require the library

```js
// ./src/App.js

import logo from './logo.svg';
import './App.css';

const { Client } = require('@elastic/elasticsearch')

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```
- `npm start`
- error reported int he browser:

> TypeError: Cannot read property 'split' of undefined
> (anonymous function)
> [node_modules/@elastic/elasticsearch/index.js:7](https://github.com/elastic/elasticsearch-js/blob/master/index.js)

- code snippet in the error:
```
   4 | 
   5 | 'use strict'
   6 | 
>  7 | const nodeMajor = Number(process.versions.node.split('.')[0])
   8 | 
   9 | const { EventEmitter } = require('events')
  10 | const { URL } = require('url')
```

## Expected behavior

the module should be required without error

## Debugging

I did `console.log(process.version.node);` in `node_modules/@elastic/elasticsearch/index.js`. It looks to me that process.versions.node is undefined.

## Your Environment

- *node version*: was v12.18.4 upgraded to v14.15.0 same issue
- `@elastic/elasticsearch` *version*: 7.9.1
- *os*: Mac
- *any other relevant information*:

**Comment by spyderman4g63** [comment]
Sorry, I think I am confused. I don't think this library was designed to be used directly in react.js. I believe that value is empty because react is executed client-side.

**Comment by vikiival** [comment]
Reopen issue please, npm modules should work also with client libs such as React or Vue.

Rationale: fast prototypes

**Comment by delvedor** [comment]
> npm modules should work also with client libs such as React or Vue.

@vikiival I don't agree, some libraries can work in both environments, others can't.
It's not safe connecting directly to Elasticsearch from the browser, as it will expose you to security risks, hence we do not support it.
You can write a small node.js proxy for sending queries and make the browser communicate with your proxy.

**Comment by andreasanta** [comment]
@delvedor I am also having this issue, but exposing an ElasticSearch cluster to the web does not really entail security risks if your indices are protected properly and your infra is properly configured. On the contrary, it allows fast low latency query from the front end when interrogating ES from the browser. Would you please re-open the issue? 🙇

**Comment by delvedor** [comment]
@andreasanta Even if your cluster is properly configured, and you are using an ES user with very low permissions, an attacker could still send heavy queries and overload the cluster.
Would you ever expose postgres/mongodb to the world?

**Comment by waymorphood** [comment]
I am getting this same error in a Vue app. Is this package supported for Vue?

**Comment by vikiival** [comment]
> I am getting this same error in a Vue app. Is this package supported for Vue?

Unfortunately not :/ 

 >  Even if your cluster is properly configured, and you are using an ES user with very low permissions, an attacker could still send heavy queries and overload the cluster.
 
@delvedor:
 The main reason I try to reopen this issue are fast prototypes, not real-world applications. 
Think of it as [evolutionary prototyping](https://link.springer.com/referenceworkentry/10.1007%2F978-1-4020-8265-8_201039)

**Comment by spyderman4g63** [comment]
If recall correctly, I was able to hardcode a nodeMajor constant to get it to work in react. I eventually switched to using a node.js proxy between the react.js app and elasticsearch.

```
// in node_modules/@elastic/elasticsearch/index.js

// replaced this line 
const nodeMajor = Number(process.versions.node.split('.')[0])

// with something like this
const nodeMajor = 14.15.0
```

I can't say that everything would work but it might be OK for a rapid prototype.

**Comment by andreasanta** [comment]
I solved it reverting to the legacy client: https://www.npmjs.com/package/elasticsearch

> @andreasanta Even if your cluster is properly configured, and you are using an ES user with very low permissions, an attacker could still send heavy queries and overload the cluster.
> Would you ever expose postgres/mongodb to the world?

PostGres and MongoDB are read-write databases that can contain sensitive information. I would not expose them for security reason. But just the search endpoint of ElasticSearch is a perfect candidate for me for direct JS access. What's the use of introducing a BE middleware that perform just request throttling? Maybe I'm missing something, but the comparison with DBs is a bit daring :)

**Comment by catonice** [comment]
What is the correct way to query an index then from ES (as shown in dev tools)? I'm new to ES and am struggling with the lack of documentation for creating a Kibana Plugin based in ReactJS. I want to run queries/post requests from the plugin. TIA

**Comment by careylzh** [comment]
> If recall correctly, I was able to hardcode a nodeMajor constant to get it to work in react. I eventually switched to using a node.js proxy between the react.js app and elasticsearch.
> 
> ```
> // in node_modules/@elastic/elasticsearch/index.js
> 
> // replaced this line 
> const nodeMajor = Number(process.versions.node.split('.')[0])
> 
> // with something like this
> const nodeMajor = 14.15.0
> ```
> 
> I can't say that everything would work but it might be OK for a rapid prototype.
Hi could you kindly give the exact details of how you got it to work? Am now running a reactjs project, db configured on aws elasticsearch already. Thanks!!!

**Comment by halmos** [comment]
Just to a comment to vote in favor of re-opening this issue and supporting browser applications. It is certainly possible to have a secure ES instance without the need of a proxy. In our case we use AWS's Elasticsearch service along with AWS's Cognito and IAM authentication to grant the client restricted access only to verified users. 

In any case, It seems to me that the SDK should not be opinionated about how to secure the server. 

It should also be noted that the legacy sdk did support browser environments.

**Comment by anvyidol** [comment]
![image](https://user-images.githubusercontent.com/82250843/220132156-7aa571ec-9300-4247-ac93-a8790b38471f.png)
i have a error similar. But with me, I require 'dotenv' before config and this help me.

**Comment by himalayaahuja** [comment]
@anvyidol Could you explain a little more?

Also @spyderman4g63 this is failing with the same error while executing e2e tests. So how do we fix that..since this is actually a node environment and supposed to be running with tests.
Please reopen this and advise.

**Comment by himalayaahuja** [comment]
@delvedor ??

**Comment by vikiival** [comment]
3 years later and I still get notifications for this issue 🥺

**Comment by himalayaahuja** [comment]
@vikiival But mine's a valid use case!! 😃

**Comment by JoshMock** [comment]
Hey friends. @delvedor has not been the maintainer of this repo for over a year now. I took over a few months ago and have been catching up on these long-running conversations.

[As of now](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/es-security-principles.html#security-protect-cluster-traffic) we still officially discourage exposing Elasticsearch instances to the open internet. That said, I know there are use cases where security is not an immediate concern, like when prototyping or running on a private network. So I totally get the frustration.

I also want to clarify that the client isn't very opinionated about how to secure a server. We support connecting over both HTTPS and HTTP, and with or without authentication credentials. The specific client bug addressed here was not intentionally blocking browsers, it was just a side effect of writing a client that was built with the assumption that it would run on a server.

In order to fully support the browser runtime environment, several things would need to happen beyond just fixing `process.version` type bugs:

- shim or replace all necessary usage of core Node.js modules and other dependencies
- ensure core functionality like connection-pooling, node-sniffing, certification verification, etc. all works as expected
- block and/or log warnings for optional functionality that will not work
- build a test matrix to verify the client works on most common browser runtimes and devices (probably including mobile)
- fix any significant blockers found during that process

All that to say: the effort required to support all of that would require time that I as a single maintainer don't have right now. My primary focus is preparing the client for upcoming Elasticsearch functionality and addressing a large backlog of open issues and PRs. Setting up a proxy for ES requests, as has been suggested here, is both more secure and far less effort to build. There are plenty of examples here and elsewhere for how to do that.

Finally, PRs to this repo from the community that remove blockers to browser support are more than welcome, and would be considered seriously. This is also an Apache 2.0-licensed project, so all are welcome to fork it and release a version that solves these problems.
