### ISSUE TITLE
EPIPE error

### ISSUE THREAD

**Issue by lyykfi** [elastic/elasticsearch-js#1595]
## 🐛 Bug Report

Hi folks,
Time to time I've faced the error when I push my logs to elasticsearch: Uncaught Exception \t{\"errorType\":\"Error\",\"errorMessage\":\"write EPIPE\",\"code\":\"EPIPE\",\"errno\":\"EPIPE\",\"syscall\":\"write\",\"stack\":[\"Error: write EPIPE\",\" at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)\"]}

## To Reproduce

It happen randomly in AWS lambda and more frequently in a Meteor app.

```js

const client = new Client({
			node: options.elastic.host,
			auth: options.elastic.auth,
			disablePrototypePoisoningProtection: true,
		})
		const elasticTransport = new ElasticsearchTransport({
			client,
			indexPrefix: 'logstash',
			buffering: false,
			transformer: (logData) => {
				let transformed = ElasticsearchTransformer(logData)

				// workaround for meteor.
				const timestamp = transformed['@timestamp']
				transformed['@timestamp'] = isValidISODateString(timestamp)
					? timestamp
					: new Date().toISOString()

				// add labels
				transformed = {
					...transformed,
					...(options.labels as any),
				}

				return transformed
			},
		})

		myTransports.push(elasticTransport)
```

## Your Environment

- *node version*: 12
- `@elastic/elasticsearch` *version*: 7.15.0

**Comment by delvedor** [comment]
Hello! This error looks unrelated to the client. Can you provide an example to reproduce the issue?
I don't know what `ElasticsearchTransport ` is.

**Comment by PhaedrusTheGreek** [comment]
I'm also experiencing this error under the following conditions:

Called method:

```
client.bulk({ body });
```

Response from Elasticsearch is `413: Entity Too Large`, and NodeJS it terminating abnormally like this:

```
2021-12-15 10:49:47.246 debug [my-module] Sending 1000 documents to Elasticsearch
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

In [a related discussion](https://github.com/nodejs/help/issues/2034), there is a `413: Payload Too Large` error being observed from another system (not Elasticsearch), but is resulting in the same EPIPE error.   In that issue, it is described as happening when one side is streaming data to an open connection, and the other side suddenly closes the connection.  

Since the 413 error is standard, it seems logical that both systems close the stream and perhaps NodeJS doesn't like that.   

The main problem in my case is that this error does not seem to be catchable.
