### ISSUE TITLE
Provide a codemod for the removal of the body key

### ISSUE THREAD

**Issue by ddolcimascolo** [elastic/elasticsearch-js#1637]
:sweat_smile:  Part of my "Upgrading to v8 is too complicated" series of issues

## 🚀 Feature Proposal

In my codebase, I have more than 500 custom Elasticsearch queries written as Javascript file, in the form of

```
export default {
  index: 'my-index',
  filter_path: '...',
  etc...,
  body: {
    size: 1,
    query: {
      ...
    },
    etc...
  }
}
```

In the changelog you mention **Migration effort: Small** for this breaking change. To be honest it's certainly the larger breaking change of this upgrade to v8 :(  
For the time being, I just abandonned the change because you're still supporting the body key (thanks for that!) and I can't afford the refacto. 

My proposal is to provide a [jscodeshoft](https://github.com/facebook/jscodeshift) codemod to help your users upgrade smoothly. 

## Motivation

Upgrade effort is too large.

Thx,
David

**Comment by delvedor** [comment]
Hello! Yes, given that someone could have many requests that are using `body`, we have decided to support both methods for at least the entire v8 release.
Typescript enabled editors should help you identify code that needs to be updated and suggest how to update it when needed.

Regarding the codemod is a good idea, but since both methods are supported, it's not a priority at the moment.

**Comment by ddolcimascolo** [comment]
Thx for the reply @delvedor

I totally agree that priority is low atm. Moreover, I might find some time to contribute the codemod, I'll keep you posted.

Cheers,
David
