### ISSUE TITLE
@elastic/elasticsearch and aws-sdk-v3

### ISSUE THREAD

**Issue by BKSnake** [elastic/elasticsearch-js#1661]
## 💬 Questions and Help

Hello

Could you help me? How can I make client connaction @elastic/elasticsearch -> Client by aws-sdk-v3?

Thanks

**Comment by delvedor** [comment]
Hello! Can you post an example of what you are trying to achieve?

**Comment by BKSnake** [comment]
"@elastic/elasticsearch": "7.13.0",

```
const AWS = require('aws-sdk');
const createAwsElasticsearchConnector = require('aws-elasticsearch-connector');
const { Client } = require('@elastic/elasticsearch'); //eslint-disable-line global-require

try {
    const esClient = new Client({
        ...createAwsElasticsearchConnector(AWS.config),
        node: `https://${ELASTIC_CACHE}`,
        maxRetries: 5,
        requestTimeout: 60000,
    });

    esClient
} catch (error) {
    console.log('Error -> ', error);
}
```

**Comment by BKSnake** [comment]
I goal to make connection to elasticsearch in aws using aws-sdk3.

**Comment by technige** [comment]
@BKSnake In order to be able to help you, we need to be able to understand your full environment (client and server), the code that you have tried (which you have supplied above) and any errors or failures that you see, in full.

In addition, a clear, textual description of your use case will help us to see what might be going wrong. Without all of this, we will not be able to offer any concrete assistance.
