### ISSUE TITLE
Default ping timeout needs to be configurable.

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch-js#185]
Currently, the ping timeout defaults to 100ms and the only way to modify it is by modifying the underlying client spec.

Workaround: 
```js
Client.apis[config.apiVersion].ping.spec.requestTimeout = customDefaultMs;
```

**Comment by truongduy134** [comment]
My company is using Elasticsearch. And we have the problem that dead connection (after socket hangs up) cannot be revived because the timeout defaults to 100ms (When we try to ping elasticsearch server from our host, it usually takes 1500ms to succeed).

After looking into the source code of eslasticsearch-js and some debugging, I do not think your workaround. It is because when a connection is dead, Elasticsearch attempts to revive the function by calling https://github.com/elasticsearch/elasticsearch-js/blob/3.1/src/lib/connection_pool.js#L184-191 , which then calls **ConnectionAbstract.prototype.ping = function (params, cb) { ... }** in connection.js . But since no params is passed, requestTimeouts defaults to 100ms (which is defined inside the function) (https://github.com/elasticsearch/elasticsearch-js/blob/3.1/src/lib/connection.js#L54) . So the workaround value is not used at all for internal ping when attempting to revive a connection.

**Comment by mantoni** [comment]
This fits with my observations as well. We still have this issue, even if the workaround is applied.

**Comment by spalger** [comment]
Nice catch. I'm on it

**Comment by jage** [comment]
@spalger Isn't this fixed with https://github.com/elastic/elasticsearch-js/commit/307dc443164a87ff9175d12688419e36060ef214?

**Comment by spalger** [comment]
Yep, thanks @jage
