### ISSUE TITLE
The requestTimout setting is not working due to hard-coded 30s timeout

### ISSUE THREAD

**Issue by nemphys** [elastic/elasticsearch-js#1999]
I was trying to find what was causing a weird issue I was facing while using the reindex API (with wait_for_completion=true) when I started digging through the code to see why my requestTimeout setting was not respected.

After reading the following comment inside UndiciConnection.js:
        // undici does not support per-request timeouts,
        // to address this issue, we default to the constructor
        // timeout (which is handled by undici) and create a local
        // setTimeout callback if the request-specific timeout
        // is different from the constructor timeout.
I realised that all requests actually have a *hard-coded* 30s request timeout, set in BaseConnection.js by the following line:

`this.timeout = (_f = opts.timeout) !== null && _f !== void 0 ? _f : 30000; <---- this is the problem`

Further debugging revealed that it is actually possible to change this by specifying the Client's node setting as an object with a 'timeout' property , eg.
```
let test = = new Client({
       node: {
           url: 'xxxxxxxxxx',
           timeout: 600000
       }
});
```
but this is only applied to the initial connection if sniffing is used and is totally ignored when initializing connections as a result of sniffing.

A simple solution would be to use a huge value for the hard-coded timeout (since it acts as an upper limit for the actual timeout)!

**Comment by nemphys** [comment]
Just realized that this is exactly the same as #1791, filed 10 months ago!

Shouldn't bugs like this be addressed sooner?

**Comment by JoshMock** [comment]
They absolutely should. I'm the new maintainer of this project as of a few months ago, and before that this project had no maintainer for about a year. Since I took over, I've been juggling bug fixes while catching up with Elastic's top priorities for the clients (not all of which are immediately visible to the community). So far that has worked out to a couple notable bug fixes for each minor release of the client. I'm hopeful that in the next few months I'll be able to increase that momentum. 

In the meantime, I'll close this in favor of #1791. Thanks for your concern!
