### ISSUE TITLE
KnnQuery interface is not complete

### ISSUE THREAD

**Issue by bijela-gora** [elastic/elasticsearch-js#2013]
## 🐛 Bug Report

According to [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/search-search.html) [the KnnQuery interface](https://github.com/elastic/elasticsearch-js/blob/59caa7be59c0bda1d95e60495955a92b974dd0cf/src/api/types.ts#L2266) must contain optional property `similarity` (type `float`).

Because of the missing `similarity` property on `KnnQuery` interface it is inconvenient to use `.search` API:

![Screenshot from 2023-09-19 23-59-47](https://github.com/elastic/elasticsearch-js/assets/102924398/2d91a64d-ae1b-4e52-91d0-0cc1023e91f4)

Additionally to that `k` and `num_candidates` properties should have type of `integer`.

## Expected behavior

```ts
export interface KnnQuery {
  field: Field
  query_vector?: QueryVector
  query_vector_builder?: QueryVectorBuilder
  k: integer
  num_candidates: integer
  similarity?: float
  boost?: float
  filter?: QueryDslQueryContainer | QueryDslQueryContainer[]
}
```

**Comment by JoshMock** [comment]
Thanks for the report! I'll take a look soon.

Most type definitions in this repo are automatically generated using the specification Elastic maintains in the [elastic/elasticsearch-specificaton](https://github.com/elastic/elasticsearch-specification/) repo. I'll see if the issue can be resolved there first, so that all clients can benefit from the improvement.

In the meantime, as with any build-time TypeScript error, you can always use [ignore instructions](https://smartdevpreneur.com/typescript-eslint-ignore-and-disable-type-rules/) to skip over typing bugs that you know will not result in errors at runtime.

**Comment by bijela-gora** [comment]
@JoshMock hi

Thanks for your time and attention here.

There is event PR opened https://github.com/elastic/elasticsearch-specification/pull/2261 and I think it is ready to be merged. But I added small suggestion: https://github.com/elastic/elasticsearch-specification/pull/2261#issuecomment-1728360854

**Comment by JoshMock** [comment]
https://github.com/elastic/elasticsearch-specification/pull/2261 is merged and backported. This will be fixed in upcoming patch and minor version releases.
