### ISSUE TITLE
RequestAbortedError: Request aborted

### ISSUE THREAD

**Issue by sibelius** [elastic/elasticsearch-js#2022]
## 🐛 Bug Report

When doing a lot of document indexing in parallel

```jsx
const esClient = new Client({
      node: config.ELASTICSEARCH,
      maxRetries: 2,
      requestTimeout: 3000,
    });

await esClient.index(document);
```

it is throwing this error:

```
RequestAbortedError: Request aborted
at SniffingTransport.request (/us/ src/app/node_modules/@elastic/transport/lib/Transport.js:502:46)
at processTicksAndRejections (node:internal/process/task_ queues :95:5)
at runNextTicks (node:internal/process/task queues :64:3)
at listOnTimeout (node:internal/timers: 540:9)
at process.processTimers (node:internal/timers:514:7) {
```

## To Reproduce

Paste your code here:

```jsx
const esClient = new Client({
      node: config.ELASTICSEARCH,
      maxRetries: 2,
      requestTimeout: 3000,
    });

await esClient.index(document);
```

Try to index a lot of documents at the same time: 10k or more at the same time

## Expected behavior

It should work.
It should reuse connections
maybe old keepAlive option helped 

is there better way to start an elastic search client for production use?

Paste the results here:

not working

## Your Environment

- *node version*: 16, 18, 20
- `@elastic/elasticsearch` *version*: 8.9.0
- *os*: mac and linux

**Comment by sibelius** [comment]
it also throws like this

```
ConnectionError: Socket connection timeout
at SniffingTransport.request (/usr/src/app/node_modules/@elastic/transport/lib/Transport.js:528:31)
```

**Comment by JoshMock** [comment]
Depending on how many concurrent open connections your code is making to Elasticsearch, and how your Elasticsearch instance's networking is configured, this is more likely a networking error when connecting with Elasticsearch than a bug in the client code itself.

If you intend to index thousands of documents at once, you can do it much more efficiently  the [bulk API](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_bulk) or the [bulk API helper](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-helpers.html#bulk-helper), which lets you index many documents per request rather than one request per document, lowering the networking overhead significantly.

It looks like you tested this in multiple versions of Node.js, but I did also want to point out that [there was a bug in Node 20.0.0](https://github.com/nodejs/node/issues/47822) that caused a socket connection timeout error, which was patched in 20.3.0.

I'm going to close this for now. Feel free to reopen with more details if you discover if your problem persists.

**Comment by sibelius** [comment]
we are at node 20.2.0

how many concurrent inserts are a problem? 1k? 10k?

can I use something like a pool? like this

https://github.com/elastic/elasticsearch-js/issues/16#issuecomment-287509338

**Comment by JoshMock** [comment]
The [HTTP `Agent`](https://nodejs.org/api/http.html#new-agentoptions) in [`@elastic/transport`](https://github.com/elastic/elastic-transport-js) has `keepAlive` enabled b y default, so existing connections can be reused. If you want to create and manage your own connection pool, [the docs](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/advanced-config.html) has several examples for how to do so.

As for how many concurrent inserts are a problem, it depends on how your Elasticsearch instance is configured and what resources are available to it. High amounts of concurrent requests [are bound to available CPU threads](https://www.elastic.co/guide/en/elasticsearch/reference/current/high-cpu-usage.html). High indexing pressure can use a lot of memory, too, [but is dependent on how `indexing_pressure.memory.limit` is configured](https://www.elastic.co/guide/en/elasticsearch/reference/current/rejected-requests.html) and defaults to 10% of available heap.

In your particular case, I'm also noticing that you have configured `requestTimeout` to 3 seconds, where the default is 30 seconds. This could also lead to the `RequestAbortedError` you're experiencing, if Elasticsearch is unable to respond in under 3 seconds. Try removing that setting to see what impact it has.
