### ISSUE TITLE
Nuxt 3 compatibility

### ISSUE THREAD

**Issue by lennarddevelop** [elastic/elasticsearch-js#2131]
## 💬 Questions and Help

When in Nuxt 3 I want to use the Client. I keep getting the same error: "Class extends value undefined is not a constructor or null." 
[Here](https://stackblitz.com/edit/github-zqjbfo-k8daox?file=app.vue) I made a minimal reproduction of the problem. https://stackblitz.com/edit/github-zqjbfo-k8daox?file=app.vue

**Comment by JoshMock** [comment]
@lennarddevelop What environment are you running your Nuxt code in? [We have an open issue](https://github.com/elastic/elasticsearch-js/issues/2032#issuecomment-1870054295) around supporting edge compute environments, so if that's where you're seeing problems, it's because we haven't built support for it yet

**Comment by haidertm** [comment]
Getting same issue

![image](https://github.com/elastic/elasticsearch-js/assets/95686585/038d0965-c6b3-44ff-8535-fe5e14527d0a)

**Comment by matthieuv-chabe** [comment]
still nothing ?

**Comment by lennarddevelop** [comment]
I could not make this work. So I skipped it. 

Now I just connect to the "client" in the server directory. https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-connecting.html

Then you can just use useFetch from a component and fetch the elastic data.
