### ISSUE TITLE
Docs for putLifecycle has wrong parameters

### ISSUE THREAD

**Issue by mltsy** [elastic/elasticsearch-js#2295]
## 🐛 Bug Report

[This documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/8.14/api-reference.html#_put_lifecycle) indicates that putLifecycle has a single string parameter (named policy).  It actually takes the following parameters, neither of which are named "policy":

```js
  name: string - the identifier for the policy
  body: object - the request body sent to the API endpoint (the policy definition)
```

I couldn't find an easy way to put in a PR to fix this, as these docs appear to be auto-generated, but the [API adapter code itself](https://github.com/elastic/elasticsearch-js/blob/db911746a0d05b676f6502d31bffc39ff565f6b1/src/api/api/ilm.ts#L243) doesn't have any matching documentation... (perhaps there's an issue with the generator?)

**Comment by JoshMock** [comment]
It's actually possible to pass `body` for all API calls, as each API accepts a flattened request object, or one that includes a `body` property. The type you're looking for is documented [here](https://github.com/elastic/elasticsearch-js/blob/db911746a0d05b676f6502d31bffc39ff565f6b1/src/api/typesWithBodyKey.ts#L10264-L10272).

It's not explicitly documented that this is possible, because this was how the 7.x client worked and so was included to make migrating to the 8.x client easier. Ideally everyone would eventually switch to use the 8.x flattened request object style, so that we can remove the usage of `body` when we release a 9.x client.

Is that helpful?

**Comment by mltsy** [comment]
Hmmm... I guess I'm still confused as to the "new" format as documented then.  It says it's an object with a single "policy" attribute that is a string? (unless I'm misreading it)  Can you give a simple example of how I would create a policy using this format?  (How do I define both the name and the policy attributes using a single string?)

**Comment by JoshMock** [comment]
Ah, I was confused about your question. It does look like the code that generates the API docs somehow missed some parameters that should be included there. I'll keep this open and try to address that soon.

**Comment by JoshMock** [comment]
In the meantime, the actual TypeScript type for this request is accurate:

https://github.com/elastic/elasticsearch-js/blob/db911746a0d05b676f6502d31bffc39ff565f6b1/src/api/types.ts#L10093-L10098

**Comment by mltsy** [comment]
Ah!  Okay, great, so a name string and a policy object :+1:  Thanks for that tip, and for taking a look at fixing the docs! :)
