### ISSUE TITLE
Add response headers 

### ISSUE THREAD

**Issue by rashidkpc** [elastic/elasticsearch-js#277]
It looks like the client doesn't currently provide response headers. This is especially important when an error is received. For example, when proxying authentication up to a browser as the result of a backend REST API you may need to parse out and replicate the realm supplied by the elasticsearch server.

**Comment by spalger** [comment]
In order to make this work we will probably need to introduce a new generally accepted parameter, something like `returnResponse` which will respond with the actual http response rather than just the body. This would provide access to things like headers without loosing the current contract or responding with just the body.

**Comment by spalger** [comment]
After discussion with the rest of the clients, we decided to take a simpler approach and expose the `www-authenticate` header on 401 errors. Added in eb90ccb8067b84b6a41d0ceb53e83c8e47500db6 and released in 9.0.0.
