### ISSUE TITLE
set http.agent to false

### ISSUE THREAD

**Issue by jochenonline** [elastic/elasticsearch-js#327]
Due to [this issue](https://github.com/nodejs/node-v0.x-archive/issues/6833) it is necessary to have the possibility to set the http.agent to `false`. While doing a bulk insert into elastic I get `no living connections available` aka `EADDRNOTAVAIL`.

**Comment by spalger** [comment]
Okay, so I read through the linked issue and found this from https://github.com/nodejs/node-v0.x-archive/issues/4769 (the source issue).

> With an Agent configured for {keepAlive:false}, it will reuse connections only if there is a backlog (so it may actually use "Connection: keep-alive" under load; probably best to think of {keepAlive:false} more like forcing {maxFreeSockets:0} than anything else).

and 

> if you request with {agent:false} your request gets a new single-use agent instance w/defaults; i.e. it has the {keepAlive:false} behavior of the first bullet point above but is also guaranteed not to be reused since only the one request will ever be in its backlog.

I'm not sure how this is supposed to solve the issue you are experiencing; you will still run out of file descriptors eventually by setting `agent: false` since nothing is queued

**Comment by jochenonline** [comment]
Setting `agent: false` **does** solve the problem! This has been the case with the nodejs-only example in the [linked issue](https://github.com/nodejs/node-v0.x-archive/issues/6833) and is of course the same when doing bulk inserts in elasticsearch, because this is the same setup: at the end there are also many (many!) http requests from nodejs against an http-server. 

So this is not a theoretical problem with a theoretical solution, but a really existing problem with a approved solution. The nodejs guys say the same, but unfortunately they have not fixed the problem corretcly after two years.

**Comment by spalger** [comment]
Can you link to a comment where someone says that `agent: false` solves the problem? I have seen your results but as the first comment mentions that is probably just slowing down the problem (since there isn't any queuing).

**Comment by jochenonline** [comment]
So here you are right. From that perspective it *probably* does not solve the problem, but at least solves the symptom. So the question is, if you will  allow the API-user to decide, wether to set the agent to `null` or not. In the latter case I have to use our fork.

**Comment by jochenonline** [comment]
Your Solr equivalent did [that](https://github.com/lbdremy/solr-node-client/commits?author=jochenonline).

**Comment by spalger** [comment]
I originally planned to refer you to [this gist](https://gist.github.com/spalger/8cf4977d6ac871a5f1e2/e200e07a8e55c3068b98a138c0ad8deaff12c529) which I have pointed to several times in the past when users wanted to modify the node.js agent.

Rather than just doing that though, I submitted #329 which will allow you full control over the Agent that each http(s) backed connection will use. In order to accomplish your goal you would simply do:

```js
var client = new elasticsearch.Client({
  createNodeAgent() {
    return false
  } 
})
```

Would you mind giving the PR a look and seeing if it works for you?

**Comment by jochenonline** [comment]
Works perfectly!
