### ISSUE TITLE
Using bulk() method writing to es and sometimes get error response

### ISSUE THREAD

**Issue by yuz11** [elastic/elasticsearch-js#354]
I'm using bulk() method to write to es,and it works.
but sometimes(1 out of 10 times),I will get an error resp
I print the status and the message,is like:

Error Status:400
[action_request_validation_exception] Validation Failed: 1: index is missing;2: index is missing;

Not sure what it means as I just write to one index and it's exist. And google won't give an answer.
Could U guys give me some advice to solve it?

**Comment by spalger** [comment]
You should try turning on trace logging so that you can see the requests and responses between the client and elasticsearch. Then you will probably see where the error is. Sorry to say it, but there is probably an error in your code. If you link to the code (use https://gist.github.com if it's not already online) I can try to help you debug.

**Comment by yuz11** [comment]
find out that is the bulk data not matching
