### ISSUE TITLE
Client throws weird error when passing immutable config

### ISSUE THREAD

**Issue by kraf** [elastic/elasticsearch-js#447]
I get the error `no living connections` when I pass a frozen object into the Client constructor, e.g.

``` js
const config = Object.freeze({host: 'localhost:9200'});
const client = new elasticsearch.Client(config);

client.create(...) // => fails
```

The passed config object is mostly likely being mutated and reused by the client. Node is silently ignoring change operation on frozen objects without throwing errors so usually random stuff happens.

**Comment by spalger** [comment]
Yeah, that is definitely the case. It's unfortunate, but fixing the mutations to the config object isn't something I have time to do right now. Perhaps there is some checking we could do, but I think it would make more sense to just switch to strict mode so that the runtime will throw errors on attempted mutations (and communicate to users that they need to give esjs a mutable object).
