### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by akshayKrSingh** [elastic/elasticsearch-js#454]
Getting a Bad Request response while using **elasticsearch** **node** client.

```javascript
elastic.search({
      query:{match_all: ""}
    }, function(error, response) {
      if (error) {return console.log(error);}
      console.log("Found {" + response.hits.total + "} items in " + response.took + "ms");
      _.each(response.hits.hits, function(hit, index) {
        console.log(hit);
      });
    });
```

The above code works when I am initializing the client like below:
```javascript
var elastic = new elasticsearch.Client({host: "example.com:9200"}); // Using hostname and port number
```
But if I initialize the same, with something like below, it returns **400 Bad Request**
```javascript
var elastic = new elasticsearch.Client({host: "example.com/elasticsearch"}); // Using url
```
The only difference I could figure out was that I did not use the port, but rather used the DNS url.

**Comment by spalger** [comment]
@akshayKrSingh 400 Bad Request is being sent back by the application receiving the request, and isn't a bug in the client. Please use the [community forums](https://discuss.elastic.co/c/development) for troubleshooting as there are a lot more people able to help out there.

I suggest you turn on trace logging so that you can see the exact request the client is making and the responses it is receiving:

```js
var elastic = new elasticsearch.Client({host: "example.com/elasticsearch", log: "trace"});
```

**Comment by akshayKrSingh** [comment]
@spalger ok will try that. Thanks 👍
