### ISSUE TITLE
Aggregation always returns 10 buckets

### ISSUE THREAD

**Issue by aluminick** [elastic/elasticsearch-js#570]
I've already set the size to more than 10 but the aggregation still returns 10.

**Comment by spalger** [comment]
Hey @aluminick, hopefully you found a solution to this. This issue tracker is for bugs reports and feature requests, for general questions I suggest asking your question at https://discuss.elastic.co/. When you do, be sure to include a copy of the code you're using so that people can see what your aggregation params looks like.
