### ISSUE TITLE
long numbers mismatched with returned results

### ISSUE THREAD

**Issue by OzqurYalcin** [elastic/elasticsearch-js#648]
Elasticsearch version : 5.6.8
Elasticsearch-js version : 14.2.2

Search query :
```json
{ "query" : { "term" : { "mid" : "180329151610840347" } }  , "_source" : { "includes" : [ "mid" ] }, "from" : 0 , "size" : 1}
```

Search code : 
```js
    EsConn.search({
        index: "index",
        type: "data",
        body: {
            _source: {
                includes: ["mid"],
            },
            query: {
                term: {
                    "mid": "180329151610840347"
                }
            },
            from: from,
            size: size
        }
    }).then((data) => {
        console.log(data.hits.hits);
    }, (err) => {
        console.log(err);
        throw err;
    });
```

Result :
```json
[ {
    "_index": "index",
    "_type": "data",
    "_id": "AWJxsdrwrp7RRchWZczW",
    "_score": null,
    "_source": { "mid": 180329151610840350 }
} ]
```

Long number (180329151610840347) mismatched with returned result (180329151610840350)

**Comment by spalger** [comment]
I assume this is because numbers greater than `9007199254740991` (the value of `Number.MAX_SAFE_INTEGER` in v8) are not "safe". I'm not 100% sure what that means, but if you enable trace logging you will *probably* see the actual JSON returned by Elasticsearch has the correct integer value, but because the value is so large `JSON.parse()` is returning the wrong value. 

You might be able to get around this by supplying a custom [JSON serializer](https://github.com/elastic/elasticsearch-js/blob/14.x/src/lib/serializers/json.js) that uses a something like [JSONBigNumber](https://github.com/wbuss/JSONBigNumber). I'm not actually familiar with this library, or the changes necessary to the way you consume these results in order to use it, but seems like it *could* work.

```js
const bignumJson = require('json-bignum');
const JsonSerializer = require('elasticsearch/src/lib/serializers/json')

class BigNumJsonSerializer extends JsonSerializer {
  serialize(val) {
    switch (typeof val) {
      case 'string':
        return val;
      case 'object':
        if (val) {
          return bignumJson.stringify(obj)
        }
      /* falls through */
      default:
        return;
    }
  }
  deserialize(val) {
    if (typeof str === 'string') {
      try {
        return bignumJson.parse(str);
      } catch (e) {}
    }
  }
}

BigNumJsonSerializer.prototype.serialize.contentType = JsonSerializer.prototype.serialize.contentType

const client = new elasticsearch.Client({
  serializer: BigNumJsonSerializer
})
```
