### ISSUE TITLE
Kerberos Support

### ISSUE THREAD

**Issue by mlucool** [elastic/elasticsearch-js#651]
Hi,

I am using elastic gold and need kerberos support. I was able to force the client to work by setting a host object and forcing the Authorization header always to be sent.

i.e.:
```
new elasticsearch.Client({
  host: 'myhost.com',
  path: '/some/path',
  port: 1234,
  protocol: 'https',
  headers: {'Authorization': 'Negotiate ' + myAuthToken}
})
```

This is poor because:
1. At some point this token will expire
2. There is no way to enable mutual authentication (i.e. verify what is returned in `WWW-Authenticate`)
3. We are over sending this header by adding it on every request

Do you have any advice on:
1. How to change my host header when the token expires? I see if I look deep enough, it is saved in a private variable.
2. Is there a hook for mutual authenticate I could use?

**Comment by mlucool** [comment]
Thanks for the tip. I built a generic version of a connector based on superagent. This allows for hooks to enable kerberos or any other type of authentication required.

Let me know if you have any feedback: https://github.com/mlucool/superagent-elasticsearch

It will be published to npm shortly.

**Comment by mlucool** [comment]
@spalger Any thoughts on the code itself? Do you see any problems with the design or missing cases to cover?

**Comment by spalger** [comment]
How important do you think supplying an agent for each request is? Connections in esjs track their connection state and the assumption is that they use the same agent for each request.

If it's not a huge deal, thikgs will probably work fine as they are, but I'd suggest getting rid of the ability to set it per request and rely on `config.createNodeAgent` for customizing `this.agent` (which is handled by the base class) and just sending superagent `this.agent`.

I'd also strongly recommend using the 
[`url.format`](https://nodejs.org/dist/latest-v8.x/docs/api/url.html#url_url_format_urlobject) api rather than [crafting the url yourself](https://github.com/mlucool/superagent-elasticsearch/blob/fecf94f88cabcc6c542f73c60d1f045439cb2000/src/SuperagentConnector.js#L43).

**Comment by mlucool** [comment]
>I'd suggest getting rid of the ability to set it per request and rely on config.createNodeAgent for customizing this.agent (which is handled by the base class) and just sending superagent this.agent.

My understanding was I should honor what is passed in reqParams. https://github.com/elastic/elasticsearch-js/blob/faa59987390ae65d1df358a5f81d192a2e1d4a51/src/lib/connectors/http.js#L117 
As shown, it would by default be equivalent. If you did not intend for something to be able to override this, why pass it in the reqParams?

> I'd also strongly recommend using the url.format api rather than crafting the url yourself.

Good call. I'll fix this

**Comment by mlucool** [comment]
https://www.npmjs.com/package/superagent-elasticsearch has been published. Please link from the extensions page!
