### ISSUE TITLE
Memory leak in transport.js when using bluebird

### ISSUE THREAD

**Issue by mattdawson** [elastic/elasticsearch-js#655]
In \src\lib\transport.js at version 12.1.3 at line 10 it had:
var Promise = require('promise/lib/es6-extensions');

It was removed in version 13 and beyond, which is fine.
But in our system we have set:
global.Promise = require('bluebird')

With the removal of the var Promise, bluebird is now being used in transport.js
When we are doing large bulks, for some reason the requests no longer garbage collect, and in the heap dump look like giant nested structure of requests with data.
This may apply to other request types also, but it showed up for us in bulk uploads.

It may be good to do a check that the native promise isn't overridden to prevent this issue in transport.js?  Or work out what's going on with bluebird.

This is with the lastest version of bluebird 3.5.1, and with all versions between 13.0.0-alpha to 14.2.2
nodejs 6LTS and nodejs 8LTS

**Comment by spalger** [comment]
Since elasticsearch-js doesn't maintain a reference to the promises it creates outside the context `transport.request()` I can't see how this could be caused by the transport. I'm assuming the promises are be getting collected by something else.

If you remove your `global.Promise = require('bluebird')` shim, does your code still work?

Can you verify that the memory leaks are gone if you never call `client.bulk()`?

Tracing memory leaks to their source can be really tricky, but there are generally signs that indicate where the leak might be occurring and I don't see any in the transport. What lead you to the conclusion that is transport.js is responsible? Can you please share screenshots, reproduction code, anything that might help me arrive at the same conclusion?

**Comment by mattdawson** [comment]
> If you remove your global.Promise = require('bluebird') shim, does your code still work?
Yes
> Can you verify that the memory leaks are gone if you never call client.bulk()?
Yes

To find the issue I checked out 12.1.3 and diffed it with 13.0.0.beta, then went through each different file copying the file from 12 to 13 trying to find where the difference was, that is how I narrowed it down to the var Promise include in transport.js

With further testing today I've tracked down how to cause the issue.
You need a combination of NODE_ENV=development and global.promise=require('bluebird')
If either of these are not set the issue does not occur.

Test files are attached:
[start.zip](https://github.com/elastic/elasticsearch-js/files/1982074/start.zip)

**Comment by mattdawson** [comment]
I see here on an issue on bluebird that may be related: https://github.com/petkaantonov/bluebird/issues/1446

".each forms a chain of the promises in the array that behaves exactly like a normal manually formed promise chain. With long stack traces the entire chain is always kept in memory so that the chain steps can be traced back."

So maybe setting development causes large stack traces.
Odd that I don't see any issue in native, or in production mode.
I'd still expect some sort of traces in production mode and thus some sort of leak.
I think, a promise in the bulk call is somehow retaining a reference to the bulk values that doesn't get retained in native.
