### ISSUE TITLE
Doing some batch updates about 50 at a time, getting console errors

### ISSUE THREAD

**Issue by osmanra2** [elastic/elasticsearch-js#673]
Once I reach about 2000 updates I get this error

![screen shot 2018-06-13 at 4 17 11 pm](https://user-images.githubusercontent.com/15219134/41376044-f24481dc-6f25-11e8-98ed-db84d8144942.png)

![screen shot 2018-06-13 at 4 23 24 pm](https://user-images.githubusercontent.com/15219134/41376082-250301c0-6f26-11e8-94bc-f41c97587e69.png)

Any ideas why this could be happening? I tried a setTimeout so it could cool down and that didn't do anything. But it seems to keep going even with these errors in the console.

**Comment by spalger** [comment]
If something is preventing elasticsearch-js from connecting to Elasticsearch it's usually outside of the node.js process.

99% of the time this is caused by a proxy (nginx, HAProxy, ELB, etc.) that has some sort of rule about either request frequency, request body size, etc.

Alternatively it's possible that elasticsearch is being overwhelmed or is blocking your client for some reason. You should be able to identify that by looking at the elasticsearch server logs.
