### ISSUE TITLE
Can't read configuration topic in docs because the navigation blocks it

### ISSUE THREAD

**Issue by dedemorton** [elastic/elasticsearch-js#735]
For the problem, see https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html

The wide example under "To Use Stable Stringification" is preventing the content from wrapping correctly, which results in the navigation overlaying the content.

Java names are always soooo long....

To fix this problem, do one of the following:

- Wrap the code example unnaturally on this lines `import DefaultJsonSerializer...` and `CustomSerializer.prototype.serialize.contentType...`
- Change the formatting of the page to avoid using a table-like structure.

We don't usually run into this problem with horizontal lists, but because you've embedded sub-lists, you get the same problem that you have with wide columns in tables. :-/

**Comment by spalger** [comment]
Should be fixed with https://github.com/elastic/elasticsearch-js/commit/8bf185bd5bbb8b4ea270dcebb8e8a2a8f55ef810, I tried option 1 but couldn't find a way to get things to wrap enough, and eventually felt like even if I could get it to work it would be too fragile. Instead I moved to a non-horizontal definition list which supports horizontal scrolling in the definitions where necessary and bolded the terms to make them a little easier to spot.
