### ISSUE TITLE
I want to know which version right for me.

### ISSUE THREAD

**Issue by drake-jin** [elastic/elasticsearch-js#823]
What is `@elastic/@elasticsearch-js:15.x.x`?
Is there `version 15.x` for the `elasticsearch` on the website? 
I want to know where is the document about `version`?

I really want to use a library for ElasticSearch-2.3.1. Is it right I use `@elastic/elasitcsearch-js:2.3.1`?

Well.. I think It's really hard to recognize specific of version.
You'd better describe it on README.md.

**Comment by delvedor** [comment]
Hello!

> What is @elastic/@elasticsearch-js:15.x.x?
> Is there version 15.x for the elasticsearch on the website?

Currently, there are two Node.js clients, the legacy one, which you can find [here](https://github.com/elastic/elasticsearch-js-legacy) and the one present in this repo, which is the new official client.
The old client didn't follow the same versioning scheme as the new one, so that's why the version is at `15.x`.
The new client strictly follows the versioning of the Elastic stack, so on npm you will find all the supported lines of Elasticsearch, `5.x` (which reached EOL a few days ago), `6.x`, and `7.x`.

> I want to know where is the document about version?

Not sure what you mean here. In the website you can access the documentation for:
- `@elastic/elasitcsearch 5.x`
- `@elastic/elasitcsearch 6.x`
- `@elastic/elasitcsearch 7.x`
- `elasitcsearch 15.x`

We are working on the documentation website to show `legacy` instead of `15.x`.

> I really want to use a library for ElasticSearch-2.3.1. Is it right I use @elastic/elasitcsearch-js:2.3.1?

You should use the legacy client, which supports old versions of Elasticsearch, but I highly recommend you to upgrade to a more recent version *(did you see our [latest](https://www.elastic.co/blog/elastic-stack-7-0-0-released) release? It's very cool!)*

> Well.. I think It's really hard to recognize specific of version.
> You'd better describe it on README.md.

From the README:
```
Compatibility

The minimum supported version of Node.js is v8.

The library is compatible with all Elasticsearch versions since 5.x,
but you should use the same major version of the Elasticsearch instance
that you are using.

# Elasticsearch 7.x
@elastic/elasticsearch@7

# Elasticsearch 6.x
@elastic/elasticsearch@6

# Elasticsearch 5.x
@elastic/elasticsearch@5
```

**Comment by drake-jin** [comment]
Anyway, Thanks a lot your polite answer.

I mean that my elastic-search daemon's version 2.3.1. So, I'm looking for the right version for the elastic search.

Surely I want to use the legacy one. but, It can't. I know that 6.x specific is changed to `application/x-www-form-urlencoded` is deprecated while transaction to a elasticsearch.

So, that I'm looking for the javascript library version fit on the elasticsearch version 2.3.1.

(Already, I use a legacy version on my company code)

**Comment by delvedor** [comment]
You should install the latest version of `elasticsearch` with
```
npm install elasticsearch
```

And then pass version `'2.4'` in the `apiVersion`configuration.
```js
const { Client } = require('elasticsearch')
const client = new Client({
  host: 'http://localhost:9200',
  apiVersion: '2.4'
})
```

I would highly recommend you to upgrade Elasticsearch since the version you are using is [no longer supported](https://www.elastic.co/support/eol).

**Comment by drake-jin** [comment]
@delvedor  Oh... Damn..... Thanks  Really! That's my point. Everything is clear.
