### ISSUE TITLE
TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by lizpark** [elastic/elasticsearch-js#905]
## To Reproduce

Paste your code here:

```js
const client6 = new elastic.Client({ node: "http://127.0.0.1:9200" });
```

![image](https://user-images.githubusercontent.com/13598499/61194519-824fa700-a6f4-11e9-8cf4-9e67ee460ea9.png)

## Your Environment

- *node version*: 8
- `@elastic/elasticsearch` *version*: >=6.0.0
- *os*: Mac
- *any other relevant information*

**Comment by delvedor** [comment]
Hello! From the log it seems that you are using the client from the browser, am I right?
In such case, there is no official support for the browser since expose your Elasticsearch instance to the rest of the world will cause you security issues eventually.
I recommend you to write a lightweight proxy that uses this client instead.

**Comment by alishah730** [comment]
so does it mean it won't work with Angular app?

**Comment by delvedor** [comment]
@alishah730 correct. The client is not intended to be used in a browser environment, and we highly discourage you to connect to Elastixcsearchh directly form the browser, see https://github.com/elastic/elasticsearch-js/issues/1066.
