### ISSUE TITLE
Issues while reindexing

### ISSUE THREAD

**Issue by GregRouet** [elastic/elasticsearch-js#917]
Hello,

I am having issues with the reindexing with callWithRequest. It works perfectly fine with indices of sizes under 130000. But for some reason I don't understand I get 2 types of errors always around 130000. 

Those issues are either : 

- Mapping errors (which I don't get whith the reindexing using kibana).
- "message": "Client request error: socket hang up"

For the last one I tried to change the keepAlive parmaeter, but I can't find the way to do it properly.

Here is my code for the reindexing: 
```
const { callWithRequest } = req.server.plugins.elasticsearch.getCluster('data');

callWithRequest(req, 'reindex', { keepAlive: false }, {
            refresh: 'true',
            body: {
                source: {
                    index: req.payload.index
                },
                dest: {
                    index: index
                }
            }
        });
```

Would you by any chance have a hint on heping me find a solution ? 

Thanks a lot!

**Comment by delvedor** [comment]
Hello!
From your code it looks like you are running it from Kibana, am I right?
How are you doing that? Can you also share the response you get?

Regarding the second error, it looks like a timeout error, by increasing the `requestTimeout` option you should be able to fix that.

**Comment by GregRouet** [comment]
Hello thanks for your answer!

I am indeed running it from Kibana with a POST method : 

 ```
server.route({
    path: '/api/omar/myapp',
    method: 'POST',
    handler: async (req, h) => {
      const result = await myApp(req);
      const res = h.response(result).type('application/json');
      return res;
    }
  });
```
And the callWithRequest is called as follows in the myApp function and more specifically in the 'reindex' one : 

```
const { index } = req.payload;

await deleteIndex(req, 'tmp-index');
await create(req, 'tmp-index', req.payload.timeField);
await reindex(req, 'tmp-index');
```

What do you mean by the response I get ? 

Yes I thought of that, but I tried already to set request timeout as follows in the .yml : 

`elasticsearch.requestTimeout: 300000000`

**Comment by spalger** [comment]
A `socket hang up` error might be caused by some other actor on the network killing the request. For long running tasks like large re-indexes it's probably best to use async task handling. Checkout the paragraph mentioning `wait_for_completion=false` at https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#_url_parameters_3

With that API you can send an initial request and then poll the tasks API to get the current status of the re-index. Doing this will prevent sockets from getting killed for being stale, and will allow you to log things like progress as well.
