### ISSUE TITLE
What happened with connectionClass?

### ISSUE THREAD

**Issue by dietkinnie** [elastic/elasticsearch-js#934]
Hello, I would like to make use of the new client and while checking https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/breaking-changes.html there are no mentions of changes to `connectionClass`, however it does not seem to be the case and I am unable to replicate the following:

```
const client = new Client({
  connectionClass: HttpAmazonESConnector,
  hosts: [process.env.ES_HOST],
  keepAlive: true,
});
```
Could you please advise how best to go around this or what I'm missing?

Cheers.

**Comment by delvedor** [comment]
Hello! You are right, it's not mentioned in the document.
That parameter is now called `Connection`. You can find the documentation [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-configuration.html#_connection).

Still, be aware that Connection classes written for the legacy client will not work with the new client. Since it looks like you are using the aws connection, take a look at https://github.com/TheDeveloper/http-aws-es/issues/63 for more information.

**Comment by robertglenn** [comment]
It seems like this Connection class expects one to override a synchronous, non-void `request` method (per the aforementioned [documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-configuration.html#_connection)), which doesn't seem to be compatible with any of the AWS methods (which either expect to be void, with a callback, or expose a promise).

A suggested solution was offered back in May, [here](https://github.com/elastic/elasticsearch-js/issues/812#issuecomment-497026054), but it seems to A) leverage async/await (which I don't believe will work with this Connection class), and B) leverage an AWS.Signers namespace, which seems to be private, per [this](https://github.com/aws/aws-sdk-js/blob/master/lib/core.js#L28) (and current experience).

**Comment by LeandroDG** [comment]
This is still very relevant to anyone using AWS ElasticSearch.

**Comment by paulvav** [comment]
Any work being done on this?

**Comment by okachynskyy** [comment]
Maybe, this package will help
https://www.npmjs.com/package/aws-elasticsearch-connector
